name: repo_viewer
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"


dependencies:
  flutter:
    sdk: flutter
  oauth2: ^2.0.0
  flutter_secure_storage: ^5.0.2
  dartz: ^0.10.0
  dio: ^4.0.4
  flutter_hooks: ^0.18.1
  hooks_riverpod: ^1.0.2
  freezed_annotation: ^0.14.3
  webview_flutter: ^2.3.1
  flash: ^2.0.3
  auto_route: ^3.2.0
  material_design_icons_flutter: ^5.0.6595
  json_annotation: ^4.4.0
  sembast: ^3.1.1
  cached_network_image: ^3.2.0
  path_provider: ^2.0.7
  path: ^1.8.0
  shimmer: ^2.0.0
  pretty_dio_logger: ^1.1.1
  material_floating_search_bar: ^0.3.6
  flutter_dotenv: ^5.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.4
  lint: ^1.7.2
  auto_route_generator: ^3.2.0
  freezed: ^0.14.5
  json_serializable: ^6.1.3


flutter:
  uses-material-design: true

  assets:
    - .env
